# corpus en C++
def generate_cpp_corpus():
    structured_lines = [
        "#include <iostream>",
        "#include <vector>",
        "#include <string>",
        "#include <map>",
        "#include <algorithm>",
        "#include <stdexcept>",
        "using namespace std;",
        "",
        "class Account {",
        "private:",
        "    string owner;",
        "    double balance;",
        "public:",
        "    Account(string o, double b): owner(o), balance(b) {}",
        "    void deposit(double amount) {",
        "        if (amount <= 0) throw invalid_argument(\"Negative deposit\");",
        "        balance += amount;",
        "    }",
        "    bool withdraw(double amount) {",
        "        if (amount > balance) return false;",
        "        balance -= amount;",
        "        return true;",
        "    }",
        "    double get_balance() const { return balance; }",
        "};",
        "",
        "class Bank {",
        "private:",
        "    map<string, Account> accounts;",
        "public:",
        "    void add_account(const string& name, double initial) {",
        "        accounts[name] = Account(name, initial);",
        "    }",
        "    bool transfer(const string& from, const string& to, double amount) {",
        "        if (accounts.find(from) == accounts.end()) return false;",
        "        if (accounts.find(to) == accounts.end()) return false;",
        "        if (!accounts[from].withdraw(amount)) return false;",
        "        accounts[to].deposit(amount);",
        "        return true;",
        "    }",
        "    void print_balances() const {",
        "        for (const auto& p : accounts) {",
        "            cout << p.first << \": \" << p.second.get_balance() << endl;",
        "        }",
        "    }",
        "};",
        "",
        "int main() {",
        "    Bank bank;",
        "    bank.add_account(\"Alice\", 1000);",
        "    bank.add_account(\"Bob\", 500);",
        "    bank.transfer(\"Alice\", \"Bob\", 250);",
        "    bank.print_balances();",
        "    return 0;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Utility functions",
        "",
        "int factorial(int n) {",
        "    if (n <= 1) return 1;",
        "    return n * factorial(n - 1);",
        "}",
        "",
        "bool is_prime(int n) {",
        "    if (n <= 1) return false;",
        "    for (int i = 2; i * i <= n; ++i) {",
        "        if (n % i == 0) return false;",
        "    }",
        "    return true;",
        "}",
        "",
        "void print_primes(int limit) {",
        "    for (int i = 2; i <= limit; ++i) {",
        "        if (is_prime(i)) cout << i << ' ';",
        "    }",
        "    cout << endl;",
        "}",
        "",
        "vector<int> fibonacci(int n) {",
        "    vector<int> seq = {0, 1};",
        "    while (seq.size() < (size_t)n) {",
        "        seq.push_back(seq[seq.size()-1] + seq[seq.size()-2]);",
        "    }",
        "    return seq;",
        "}",
        "",
        "void print_matrix(const vector<vector<int>>& mat) {",
        "    for (const auto& row : mat) {",
        "        for (int val : row) cout << val << ' ';",
        "        cout << endl;",
        "    }",
        "}",
        "",
        "vector<vector<int>> multiply_matrix(const vector<vector<int>>& A, const vector<vector<int>>& B) {",
        "    size_t n = A.size(), m = B[0].size(), k = B.size();",
        "    vector<vector<int>> C(n, vector<int>(m, 0));",
        "    for (size_t i = 0; i < n; ++i)",
        "        for (size_t j = 0; j < m; ++j)",
        "            for (size_t t = 0; t < k; ++t)",
        "                C[i][j] += A[i][t] * B[t][j];",
        "    return C;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Simulation",
        "",
        "void simulate(int steps) {",
        "    vector<int> state = {1, 0, 0};",
        "    for (int t = 0; t < steps; ++t) {",
        "        vector<int> next = {0, 0, 0};",
        "        for (int i = 0; i < 3; ++i) {",
        "            next[i] = (state[(i+1)%3] + state[(i+2)%3]) % 2;",
        "        }",
        "        state = next;",
        "        for (int x : state) cout << x;",
        "        cout << endl;",
        "    }",
        "}",
        "",
        "int main2() {",
        "    vector<vector<int>> A = {{1,2,3},{4,5,6},{7,8,9}};",
        "    vector<vector<int>> B = {{9,8,7},{6,5,4},{3,2,1}};",
        "    vector<vector<int>> C = multiply_matrix(A, B);",
        "    print_matrix(C);",
        "    simulate(10);",
        "    return 0;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// File Handling Example",
        "",
        "#include <fstream>",
        "void write_to_file(const string& filename, const vector<int>& data) {",
        "    ofstream out(filename);",
        "    for (int v : data) out << v << '\\n';",
        "}",
        "",
        "vector<int> read_from_file(const string& filename) {",
        "    vector<int> data;",
        "    ifstream in(filename);",
        "    int v;",
        "    while (in >> v) data.push_back(v);",
        "    return data;",
        "}",
        "",
        "int main3() {",
        "    auto fib = fibonacci(10);",
        "    write_to_file(\"fib.txt\", fib);",
        "    auto read_back = read_from_file(\"fib.txt\");",
        "    for (int x : read_back) cout << x << ' ';",
        "    cout << endl;",
        "    return 0;",
        "}",
        "",
        # ----------------------------------------------------------
        # Sorting, exceptions, templates, polymorphism, threads, etc.
        # ----------------------------------------------------------
        "// --------------------------------------------------------------",
        "// Sorting and Searching Utilities",
        "",
        "void bubble_sort(vector<int>& arr) {",
        "    for (size_t i = 0; i < arr.size(); ++i) {",
        "        for (size_t j = 0; j + 1 < arr.size() - i; ++j) {",
        "            if (arr[j] > arr[j + 1]) swap(arr[j], arr[j + 1]);",
        "        }",
        "    }",
        "}",
        "",
        "int binary_search(const vector<int>& arr, int key) {",
        "    int l = 0, r = arr.size() - 1;",
        "    while (l <= r) {",
        "        int mid = l + (r - l) / 2;",
        "        if (arr[mid] == key) return mid;",
        "        else if (arr[mid] < key) l = mid + 1;",
        "        else r = mid - 1;",
        "    }",
        "    return -1;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Exception Handling Example",
        "",
        "double divide(double a, double b) {",
        "    if (b == 0) throw runtime_error(\"Division by zero\");",
        "    return a / b;",
        "}",
        "",
        "void safe_division() {",
        "    try {",
        "        cout << divide(10, 0) << endl;",
        "    } catch (const exception& e) {",
        "        cerr << \"Caught exception: \" << e.what() << endl;",
        "    }",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Template Specialization Example",
        "",
        "template <typename T> T maximum(T a, T b) { return (a > b) ? a : b; }",
        "template <> const char* maximum<const char*>(const char* a, const char* b) {",
        "    return strcmp(a, b) > 0 ? a : b;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Inheritance and Polymorphism Example",
        "",
        "class Shape {",
        "public:",
        "    virtual double area() const = 0;",
        "    virtual string name() const = 0;",
        "    virtual ~Shape() {}",
        "};",
        "",
        "class Circle : public Shape {",
        "    double radius;",
        "public:",
        "    Circle(double r): radius(r) {}",
        "    double area() const override { return 3.14159 * radius * radius; }",
        "    string name() const override { return \"Circle\"; }",
        "};",
        "",
        "class Rectangle : public Shape {",
        "    double w, h;",
        "public:",
        "    Rectangle(double w_, double h_): w(w_), h(h_) {}",
        "    double area() const override { return w * h; }",
        "    string name() const override { return \"Rectangle\"; }",
        "};",
        "",
        "void print_area(const Shape& s) {",
        "    cout << s.name() << \" area = \" << s.area() << endl;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Threading Example",
        "",
        "#include <thread>",
        "#include <mutex>",
        "mutex mtx;",
        "",
        "void worker(int id, int n) {",
        "    for (int i = 0; i < n; ++i) {",
        "        lock_guard<mutex> lock(mtx);",
        "        cout << \"Worker \" << id << \" iteration \" << i << endl;",
        "    }",
        "}",
        "",
        "void launch_threads() {",
        "    thread t1(worker, 1, 3);",
        "    thread t2(worker, 2, 3);",
        "    t1.join();",
        "    t2.join();",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Simulation of a Particle System",
        "",
        "struct Particle {",
        "    double x, y, vx, vy;",
        "};",
        "",
        "void update_particle(Particle& p, double dt) {",
        "    p.x += p.vx * dt;",
        "    p.y += p.vy * dt;",
        "}",
        "",
        "void simulate_particles(vector<Particle>& particles, double dt, int steps) {",
        "    for (int t = 0; t < steps; ++t) {",
        "        for (auto& p : particles) update_particle(p, dt);",
        "        if (t % 10 == 0) {",
        "            cout << \"Step \" << t << \":\";",
        "            for (auto& p : particles) cout << '(' << p.x << ',' << p.y << \") \";",
        "            cout << endl;",
        "        }",
        "    }",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// JSON-like Serializer (simple)",
        "",
        "string serialize_map(const map<string, int>& m) {",
        "    string s = \"{\";",
        "    for (auto it = m.begin(); it != m.end(); ++it) {",
        "        s += '\\\"' + it->first + '\\\"' + \":\" + to_string(it->second);",
        "        if (next(it) != m.end()) s += \",\";",
        "    }",
        "    s += \"}\";",
        "    return s;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Main Demo",
        "",
        "int main4() {",
        "    vector<int> arr = {5,2,9,1,5,6};",
        "    bubble_sort(arr);",
        "    cout << \"Sorted: \"; for (int a : arr) cout << a << ' '; cout << endl;",
        "",
        "    int idx = binary_search(arr, 5);",
        "    cout << \"Index of 5: \" << idx << endl;",
        "",
        "    Circle c(3.0); Rectangle r(4.0, 5.0);",
        "    print_area(c); print_area(r);",
        "",
        "    safe_division();",
        "    launch_threads();",
        "",
        "    map<string,int> counts = {{\"a\",1},{\"b\",2},{\"c\",3}};",
        "    cout << serialize_map(counts) << endl;",
        "",
        "    vector<Particle> ps = {{0,0,1,1},{1,2,-0.5,0.2}};",
        "    simulate_particles(ps, 0.1, 30);",
        "",
        "    return 0;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Smart pointer and resource management examples",
        "",
        "#include <memory>",
        "#include <optional>",
        "#include <variant>",
        "#include <regex>",
        "#include <filesystem>",
        "namespace fs = std::filesystem;",
        "",
        "struct Resource {",
        "    string name;",
        "    Resource(const string& n): name(n) { cout << \"Acquired \" << name << endl; }",
        "    ~Resource() { cout << \"Released \" << name << endl; }",
        "    void use() { cout << \"Using \" << name << endl; }",
        "};",
        "",
        "void use_unique_resource() {",
        "    unique_ptr<Resource> res = make_unique<Resource>(\"temp.txt\");",
        "    res->use();",
        "}",
        "",
        "shared_ptr<Resource> make_shared_res(const string& n) {",
        "    return make_shared<Resource>(n);",
        "}",
        "",
        "void share_resources() {",
        "    auto r1 = make_shared_res(\"shared-A\");",
        "    auto r2 = r1;",
        "    r1->use();",
        "    r2->use();",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Simple observer-like pattern",
        "",
        "class Listener {",
        "public:",
        "    virtual void on_event(const string& name) = 0;",
        "    virtual ~Listener() = default;",
        "};",
        "",
        "class EventBus {",
        "    vector<Listener*> listeners;",
        "public:",
        "    void subscribe(Listener* l) { listeners.push_back(l); }",
        "    void publish(const string& name) {",
        "        for (auto* l : listeners) l->on_event(name);",
        "    }",
        "};",
        "",
        "class LogListener : public Listener {",
        "public:",
        "    void on_event(const string& name) override {",
        "        cout << \"[LOG] event: \" << name << endl;",
        "    }",
        "};",
        "",
        "class MetricListener : public Listener {",
        "    map<string,int> counts;",
        "public:",
        "    void on_event(const string& name) override {",
        "        counts[name]++;",
        "        cout << \"[METRIC] \" << name << \" -> \" << counts[name] << endl;",
        "    }",
        "};",
        "",
        "void demo_events() {",
        "    EventBus bus;",
        "    LogListener log;",
        "    MetricListener met;",
        "    bus.subscribe(&log);",
        "    bus.subscribe(&met);",
        "    bus.publish(\"startup\");",
        "    bus.publish(\"startup\");",
        "    bus.publish(\"shutdown\");",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Config loader with branching logic",
        "",
        "struct AppConfig {",
        "    string env;",
        "    string db_url;",
        "    int max_threads;",
        "};",
        "",
        "optional<AppConfig> load_config(const string& path) {",
        "    if (!fs::exists(path)) {",
        "        cerr << \"Config not found: \" << path << endl;",
        "        return nullopt;",
        "    }",
        "    AppConfig cfg;",
        "    cfg.env = \"dev\";",
        "    cfg.db_url = \"postgres://localhost:5432/app\";",
        "    cfg.max_threads = 4;",
        "    return cfg;",
        "}",
        "",
        "void init_app(const string& cfg_path) {",
        "    auto cfg_opt = load_config(cfg_path);",
        "    if (!cfg_opt) {",
        "        cerr << \"Cannot start app without config\" << endl;",
        "        return;",
        "    }",
        "    auto cfg = *cfg_opt;",
        "    cout << \"Starting in env: \" << cfg.env << endl;",
        "    if (cfg.env == \"prod\") {",
        "        cout << \"Connecting to prod DB: \" << cfg.db_url << endl;",
        "    } else if (cfg.env == \"staging\") {",
        "        cout << \"Connecting to staging DB\" << endl;",
        "    } else {",
        "        cout << \"Connecting to dev DB\" << endl;",
        "    }",
        "    cout << \"Threads: \" << cfg.max_threads << endl;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Regex-based log parser",
        "",
        "struct LogEntry {",
        "    string level;",
        "    string message;",
        "};",
        "",
        "vector<LogEntry> parse_logs(const vector<string>& lines) {",
        "    vector<LogEntry> out;",
        "    regex re(\"\\\\[(INFO|WARN|ERROR)\\\\] (.*)\");",
        "    smatch m;",
        "    for (const auto& line : lines) {",
        "        if (regex_match(line, m, re)) {",
        "            out.push_back(LogEntry{m[1].str(), m[2].str()});",
        "        }",
        "    }",
        "    return out;",
        "}",
        "",
        "void print_errors(const vector<LogEntry>& logs) {",
        "    for (const auto& e : logs) {",
        "        if (e.level == \"ERROR\") {",
        "            cout << \"ERR: \" << e.message << endl;",
        "        }",
        "    }",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Variant-based message handling",
        "",
        "struct MsgText { string text; };",
        "struct MsgNumber { int value; };",
        "using Message = variant<MsgText, MsgNumber>;",
        "",
        "void handle_message(const Message& msg) {",
        "    if (holds_alternative<MsgText>(msg)) {",
        "        cout << \"TEXT: \" << get<MsgText>(msg).text << endl;",
        "    } else if (holds_alternative<MsgNumber>(msg)) {",
        "        cout << \"NUMBER: \" << get<MsgNumber>(msg).value << endl;",
        "    }",
        "}",
        "",
        "void demo_messages() {",
        "    vector<Message> msgs = { MsgText{\"hello\"}, MsgNumber{42}, MsgText{\"bye\"} };",
        "    for (const auto& m : msgs) handle_message(m);",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// A slightly longer service-style function",
        "",
        "class UserRepo {",
        "    map<int,string> users;",
        "public:",
        "    UserRepo() { users[1] = \"alice\"; users[2] = \"bob\"; users[3] = \"carol\"; }",
        "    optional<string> get_user(int id) const {",
        "        auto it = users.find(id);",
        "        if (it == users.end()) return nullopt;",
        "        return it->second;",
        "    }",
        "};",
        "",
        "class AuthService {",
        "    const UserRepo& repo;",
        "public:",
        "    AuthService(const UserRepo& r): repo(r) {}",
        "    bool login(int id, const string& pass) {",
        "        auto u = repo.get_user(id);",
        "        if (!u) {",
        "            cerr << \"No such user\" << endl;",
        "            return false;",
        "        }",
        "        if (pass.empty()) {",
        "            cerr << \"Empty password\" << endl;",
        "            return false;",
        "        }",
        "        cout << \"User \" << *u << \" logged in\" << endl;",
        "        return true;",
        "    }",
        "};",
        "",
        "void demo_auth() {",
        "    UserRepo repo;",
        "    AuthService svc(repo);",
        "    svc.login(1, \"secret\");",
        "    svc.login(9, \"secret\");",
        "    svc.login(2, \"\");",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Filesystem traversal example",
        "",
        "void list_cpp_files(const string& root) {",
        "    if (!fs::exists(root)) {",
        "        cerr << \"Not found: \" << root << endl;",
        "        return;",
        "    }",
        "    for (const auto& entry : fs::recursive_directory_iterator(root)) {",
        "        if (entry.is_regular_file()) {",
        "            auto p = entry.path();",
        "            if (p.extension() == \".cpp\" || p.extension() == \".hpp\") {",
        "                cout << p.string() << endl;",
        "            }",
        "        }",
        "    }",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Tiny HTTP-like request parser",
        "",
        "struct HttpRequest {",
        "    string method;",
        "    string path;",
        "    map<string,string> headers;",
        "    string body;",
        "};",
        "",
        "HttpRequest parse_request(const vector<string>& lines) {",
        "    HttpRequest req;",
        "    if (lines.empty()) return req;",
        "    {",
        "        istringstream iss(lines[0]);",
        "        iss >> req.method >> req.path;",
        "    }",
        "    size_t i = 1;",
        "    for (; i < lines.size(); ++i) {",
        "        const string& line = lines[i];",
        "        if (line.empty()) {",
        "            ++i;",
        "            break;",
        "        }",
        "        auto pos = line.find(\":\");",
        "        if (pos != string::npos) {",
        "            string key = line.substr(0, pos);",
        "            string val = line.substr(pos + 1);",
        "            if (!val.empty() && val[0] == ' ') val.erase(val.begin());",
        "            req.headers[key] = val;",
        "        }",
        "    }",
        "    for (; i < lines.size(); ++i) {",
        "        req.body += lines[i];",
        "        if (i + 1 < lines.size()) req.body += '\\n';",
        "    }",
        "    return req;",
        "}",
        "",
        "void handle_request(const HttpRequest& req) {",
        "    cout << \"Method: \" << req.method << \" path: \" << req.path << endl;",
        "    if (req.method == \"GET\") {",
        "        cout << \"Serving resource...\" << endl;",
        "    } else if (req.method == \"POST\") {",
        "        cout << \"Body: \" << req.body << endl;",
        "    } else {",
        "        cout << \"Unknown method\" << endl;",
        "    }",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Finite State Machine example",
        "",
        "enum class ConnState { Disconnected, Connecting, Connected, Error };",
        "",
        "struct Connection {",
        "    ConnState state = ConnState::Disconnected;",
        "    int retries = 0;",
        "};",
        "",
        "void advance(Connection& c, bool ok) {",
        "    switch (c.state) {",
        "        case ConnState::Disconnected:",
        "            c.state = ConnState::Connecting;",
        "            break;",
        "        case ConnState::Connecting:",
        "            if (ok) {",
        "                c.state = ConnState::Connected;",
        "                c.retries = 0;",
        "            } else {",
        "                c.retries++;",
        "                if (c.retries > 3) c.state = ConnState::Error;",
        "            }",
        "            break;",
        "        case ConnState::Connected:",
        "            if (!ok) c.state = ConnState::Disconnected;",
        "            break;",
        "        case ConnState::Error:",
        "            break;",
        "    }",
        "}",
        "",
        "string state_to_string(ConnState s) {",
        "    switch (s) {",
        "        case ConnState::Disconnected: return \"Disconnected\";",
        "        case ConnState::Connecting: return \"Connecting\";",
        "        case ConnState::Connected: return \"Connected\";",
        "        case ConnState::Error: return \"Error\";",
        "    }",
        "    return \"Unknown\";",
        "}",
        "",
        "void demo_fsm() {",
        "    Connection c;",
        "    for (int i = 0; i < 6; ++i) {",
        "        bool ok = (i == 2) || (i == 5);",
        "        advance(c, ok);",
        "        cout << \"Step \" << i << \": \" << state_to_string(c.state) << \" (retries=\" << c.retries << \")\" << endl;",
        "    }",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Generic printer with SFINAE-like structure (simplified)",
        "",
        "template <typename T>",
        "void print_any(const T& v) {",
        "    cout << v << endl;",
        "}",
        "",
        "template <typename T>",
        "void print_any(const vector<T>& v) {",
        "    cout << \"[\";",
        "    for (size_t i = 0; i < v.size(); ++i) {",
        "        cout << v[i];",
        "        if (i + 1 < v.size()) cout << \",\";",
        "    }",
        "    cout << \"]\" << endl;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Long-ish algorithm with multiple loops",
        "",
        "int longest_increasing_subsequence(const vector<int>& a) {",
        "    if (a.empty()) return 0;",
        "    vector<int> dp(a.size(), 1);",
        "    int best = 1;",
        "    for (size_t i = 0; i < a.size(); ++i) {",
        "        for (size_t j = 0; j < i; ++j) {",
        "            if (a[j] < a[i]) {",
        "                dp[i] = max(dp[i], dp[j] + 1);",
        "            }",
        "        }",
        "        best = max(best, dp[i]);",
        "    }",
        "    return best;",
        "}",
        "",
        "void demo_lis() {",
        "    vector<int> v = {10,9,2,5,3,7,101,18};",
        "    cout << \"LIS = \" << longest_increasing_subsequence(v) << endl;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Small serialization-style to string builder",
        "",
        "string join(const vector<string>& parts, const string& sep) {",
        "    string out;",
        "    for (size_t i = 0; i < parts.size(); ++i) {",
        "        out += parts[i];",
        "        if (i + 1 < parts.size()) out += sep;",
        "    }",
        "    return out;",
        "}",
        "",
        "string user_to_json(const string& name, int age) {",
        "    return string(\"{\\\"name\\\":\\\"\") + name + \"\\\",\\\"age\\\":\" + to_string(age) + \"}\";",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Lambda-heavy section",
        "",
        "void demo_lambdas() {",
        "    vector<int> nums = {1,2,3,4,5,6,7,8,9};",
        "    int threshold = 5;",
        "    nums.erase(remove_if(nums.begin(), nums.end(), [threshold](int x){ return x < threshold; }), nums.end());",
        "    for_each(nums.begin(), nums.end(), [](int x){ cout << x << ' '; });",
        "    cout << endl;",
        "    int counter = 0;",
        "    auto count_calls = [&counter]() { ++counter; cout << \"calls=\" << counter << endl; };",
        "    count_calls();",
        "    count_calls();",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Iterator-like generator (manual)",
        "",
        "class Range {",
        "    int cur;",
        "    int endv;",
        "public:",
        "    Range(int s, int e): cur(s), endv(e) {}",
        "    bool has_next() const { return cur < endv; }",
        "    int next() { return cur++; }",
        "};",
        "",
        "void demo_range() {",
        "    Range r(0, 5);",
        "    while (r.has_next()) {",
        "        cout << r.next() << ' ';",
        "    }",
        "    cout << endl;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// Large orchestrator main to tie things together",
        "",
        "int main5() {",
        "    demo_fsm();",
        "    demo_lis();",
        "    demo_lambdas();",
        "    vector<string> raw = {",
        "        \"GET /index.html\",",
        "        \"Host: localhost\",",
        "        \"Content-Length: 0\",",
        "        \"\"",
        "    };",
        "    auto req = parse_request(raw);",
        "    handle_request(req);",
        "    demo_range();",
        "    return 0;",
        "}",
        "",
        "// --------------------------------------------------------------",
        "// END OF FINAL BATCH",
    ]

    return "\n".join(structured_lines)
